[theme]
primaryColor="#D4AF37"            # Brooklyn Gold
backgroundColor="#000000"         # Black
secondaryBackgroundColor="#161A1D" # Charcoal / Dark Silver
textColor="#FFFFFF"               # White
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
